name: Swagger IDE nightly build

on:
  workflow_dispatch:
  schedule:
    - cron:  '15 4 * * *'

jobs:
  nightly-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@swagger-api"
      - name: Cache npm cache files
        id: cache-npm-cache-files
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-cache-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Cache Cypress binary
        id: cache-cypress-binary
        uses: actions/cache@v2
        with:
          path: cypress/cache
          key: cypress-binary-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.SWAGGER_BOT_GITHUB_TOKEN }}
      - name: Lint code
        run: npm run lint
      - name: Execute unit tests
        run: npm test --watchAll=false
        env:
          CI: true
      - name: Build App artifacts
        run: npm run build:app
      - name: E2E Tests
        run: npm run cy:ci
      - name: Upload build artifacts (for GH pages)
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_SB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_SB_PASSWORD }}
      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: smartbear/swagger-ide:latest

  deploy:
    name: Deploy to GH Pages and Rancher

    needs: [ nightly-build ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true
    - name: Download built artifact from build job
      uses: actions/download-artifact@v2
    - name: Deploy GH-Pages🚀
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages # The branch the action should deploy to.
        folder: build # The folder the action should deploy.
        clean: true # Automatically remove deleted files from the deploy branch
    - name: Deploy Rancher🚢
      run: |
        ts="$(date +'%Y-%m-%dT%H:%M:%SZ' --utc)"
        curl -s -D /dev/stderr -X PATCH \
          -H "Authorization: Bearer ${RANCHER_BEARER_TOKEN}" \
          -H 'Content-Type: application/strategic-merge-patch+json' \
          "${RANCHER_URL}/k8s/clusters/${RANCHER_CLUSTER_ID}/apis/apps/v1/namespaces/${RANCHER_NAMESPACE}/${RANCHER_K8S_OBJECT_TYPE}/${RANCHER_K8S_OBJECT_NAME}" \
          -d "{\"spec\": {\"template\": {\"metadata\": {\"annotations\": {\"cattle.io/timestamp\": \"${ts}\"}}}}}"
      env:
        RANCHER_BEARER_TOKEN: ${{ secrets.RANCHER_BEARER_TOKEN }}
        RANCHER_CLUSTER_ID: 'c-n8zp2'
        RANCHER_NAMESPACE: 'swagger-oss'
        RANCHER_K8S_OBJECT_TYPE: 'daemonsets'
        RANCHER_URL: ${{ secrets.RANCHER_URL }}
        RANCHER_K8S_OBJECT_NAME: 'swagger-ide'
